<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RtLess\Module'                => __DIR__ . '/Module.php',
  'RtLess\Options\ModuleOptions' => __DIR__ . '/src/RtLess/Options/ModuleOptions.php',
  'RtLess\View\Helper\LessCss'   => __DIR__ . '/src/RtLess/View/Helper/LessCss.php',
);
